# Generated by Django 5.0.1 on 2024-01-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internla_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
    ]
